#ifndef PUREDARWIN_DYLD_COMPAT_SYSTEM_SYS_CONTENT_PROTECTION_H
#define PUREDARWIN_DYLD_COMPAT_SYSTEM_SYS_CONTENT_PROTECTION_H

#include "../../../../../Kernel/xnu/bsd/sys/content_protection.h"

#endif /* PUREDARWIN_DYLD_COMPAT_SYSTEM_SYS_CONTENT_PROTECTION_H */
